sudo: required
language: cpp
os: osx
osx_image: xcode9.1
compiler: clang

git:
  submodules: false

#cache:
#  directories:
#    - ${TRAVIS_BUILD_DIR}/deps/boost-1.64.0

#matrix:
#  include:
#    - compiler: gcc
#      addons:
#        apt:
#          sources:
#            - boost-latest
#            - ubuntu-toolchain-r-test
#          packages:
#            - g++-7
#            - gcc-7
#            - libboost1.55-all-dev
#      env:
#        - COMPILER=g++-7
#        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
#  - eval "${MATRIX_EVAL}"
  - brew update
  - sed -i .bk 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

#install:
  # Set env variables
#  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
#  - BOOST_VERSION=1.64.0

  # Setup deps dir
#  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}

  # Install boost
#  - |
#    BOOST_DIR=${DEPS_DIR}/boost-${BOOST_VERSION}
#    if [[ -z "$(ls -A ${BOOST_DIR})" ]]; then
#      BOOST_URL="http://sourceforge.net/projects/boost/files/boost/${BOOST_VERSION}/boost_${BOOST_VERSION//\./_}.tar.gz"
#      mkdir -p ${BOOST_DIR}
#      { travis_retry wget -O - ${BOOST_URL} | tar --strip-components=1 -xz -C ${BOOST_DIR}; } || exit 1
#      (cd ${BOOST_DIR}/tools/build && ./bootstrap.sh --with-system --with-filesystem --with-log --with-signals --prefix=${DEPS_DIR}/b2 && ./b2 install)
#    fi
#    CMAKE_OPTIONS+=" -DBOOST_ROOT=${BOOST_DIR}"
#    export PATH=${DEPS_DIR}/b2/bin:${PATH}

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - (mkdir build && cd build && cmake .. ${CMAKE_OPTIONS})

script:
  - cd build
  - make