sudo: required
language: cpp
os: osx
osx_image: xcode9.1
compiler: clang

git:
  submodules: false

before_install:
  - brew update
  - sed -i .bk 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive


before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - (mkdir build && cd build && cmake .. ${CMAKE_OPTIONS})

script:
  - cd build
  - make
  - test/x_copilot_test
