sudo: required
language: cpp
os: osx
osx_image: xcode9.1
compiler: clang

git:
  submodules: false

before_install:
  - brew update
  - sed -i .bk 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - (mkdir -p Resources/plugins && cp -r src/lib/XPSDK/Libraries/Mac/. Resources/plugins/)
  - (mkdir -p build/x-copilot && cd build/x-copilot && cmake ../.. ${CMAKE_OPTIONS})

script:
  - cd build/x-copilot
  - make
  - test/x_copilot_test
